repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - dbt-postgres==1.9.0
          - sqlfluff-templater-dbt==3.3.0
      - id: sqlfluff-fix
        stages: [manual] #  This command is available only to run manually
        additional_dependencies:
          - dbt-postgres==1.9.0
          - sqlfluff-templater-dbt==3.3.0

  - repo: local
    hooks:
      - id: dbt-compile
        name: "DBT Compile Check"
        entry: "C:/Users/onwuk/Documents/workspace/my_env/Scripts/dbt.exe compile"
        language: system
        pass_filenames: false
